# Generated by Django 5.1.6 on 2026-06-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WindyAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "windy_access_log",
            },
        ),
    ]
